#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.array([1,2,3,4,5])
print("int bytes:" , arr.nbytes )

int bytes: 40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.zeros(10) ; arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
n = int(input("enter the size: "))
arr = np.random.randint( 10 , 50 , size = n)

print(arr)

enter the size: 6
[28 29 29 20 43 29]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.array([1,2,3,45,6,7])
arr = np.flip(arr)
print(arr)

[ 7  6 45  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
 arr = np.array([1,2,0,0,4,0])
 print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
mat = np.identity(3)
mat2 = np.eye(3)
print(mat)
print("------------")
print(mat2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.rand(27).reshape(3,3,3)
print(arr)

[[[0.61869399 0.55865962 0.83110391]
  [0.37960422 0.90138649 0.89900578]
  [0.38654878 0.92298556 0.11871397]]

 [[0.46699926 0.87394218 0.76669921]
  [0.01727548 0.26475913 0.99475387]
  [0.8986661  0.34631638 0.17010138]]

 [[0.23469048 0.20354944 0.53471686]
  [0.82031935 0.03486073 0.32137533]
  [0.33997993 0.0778322  0.55627157]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.rand(100).reshape(10,10)
print("maxnumber: " np.max(arr))
print("minnumber: " np.min(arr))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
vec = np.random.rand(30)
mean = np.mean(vec)
print(mean)

0.5600607296061482


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
row = int(input("enter the rows: "))
col = int(input("enter the coluns: "))
arr = np.ones((row,col))
for i in range(1,row - 1):
  for j in range(1,col -1 ):
    arr[i][j] = 0
print(arr)

enter the rows: 5
enter the coluns: 5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
# row = int(input("enter the rows: "))
# col = int(input("enter the coluns: "))
# arr = np.random.rand(row,col)
# arr2 = np.zeros((row+2 , col +2))
# print(arr)
# for i in range(row):
#   for j in range(col):
#     arr2[i+1][j+1] = arr[i][j]
# print(arr2)
# use 4*4 3lshan tban
row = int(input("enter the rows: "))
col = int(input("enter the coluns: "))
arr = np.random.rand(row,col)
print(arr)
arr= np.pad(arr , pad_width=1 , mode ="constant" , constant_values= 0 )
print(arr)


enter the rows: 4
enter the coluns: 4
[[0.20697208 0.67018785 0.38344071 0.30838235]
 [0.08391754 0.52325703 0.20443133 0.34426739]
 [0.18800755 0.36339397 0.79781107 0.62664004]
 [0.80482134 0.84703238 0.28322424 0.83492727]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.20697208 0.67018785 0.38344071 0.30838235 0.        ]
 [0.         0.08391754 0.52325703 0.20443133 0.34426739 0.        ]
 [0.         0.18800755 0.36339397 0.79781107 0.62664004 0.        ]
 [0.         0.80482134 0.84703238 0.28322424 0.83492727 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# ######################################

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
mat = np.zeros((5,5))
l = [1,2,3,4]
j = 0
for i in range(1,5):
  mat[i][j] = l[i-1]
  j+= 1
print(mat)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# x = np.zeros((8, 8))
# x[1::2, ::2] = 1  # Setting alternate rows starting from the second row with alternate columns to 1
# x[::2, 1::2] = 1  # Setting alternate rows starting from the first row with alternate columns to 1

# # Printing the resulting checkerboard pattern array
# print(x) ###########################################

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
###############################################################

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
samp = np.array([[1,0],[0,1]])
f = np.tile(samp ,(4,4))
print(f)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
mat = np.random.rand(5,5)
det = np.linalg.det(mat)
mat = mat / det
print(mat)

[[1170.56950303   80.52554045  858.15133286  467.20503483  250.02077851]
 [1075.60612502 1070.8515454  1091.87163554  562.86506497  423.43520048]
 [ 421.4513141  1251.01090967  456.25380819  349.66673842  338.38103403]
 [ 162.48339021  443.74221924   95.94925279  538.41845131  673.08309452]
 [ 919.38905176  788.24132272  359.75668208  957.656475    949.187431  ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
dtype_rgba = np.dtype([
    ("r" , np.int32),
    ("g" , np.int32),
    ("b" , np.int32),
    ("a" , np.int32)
])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
mat1 = np.random.rand(5,3)
mat2 = np.random.rand(3,2)
print(mat1)
print()
print(mat2)
print()
mut = np.dot(mat1,mat2)
print(mut)

[[0.19184282 0.67191223 0.8913641 ]
 [0.69131833 0.51836145 0.83813116]
 [0.40686543 0.08168024 0.75141534]
 [0.24379711 0.90857213 0.4130334 ]
 [0.78318031 0.8597463  0.6088972 ]]

[[0.33643962 0.21583444]
 [0.06580826 0.2735322 ]
 [0.77751655 0.977267  ]]

[[0.80181124 1.09629664]
 [0.91836019 1.11007678]
 [0.72649875 0.84449117]
 [0.46295486 0.70478746]
 [0.79349894 0.99926072]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.random.randint(0, 25,size = 24)
print(arr)
mask = (arr>=3) & (arr<=8)
arr[mask] = -arr[mask]
print(arr)

[16  7  9 24 23  9  7 22 18  6  0 23 14 14 17 14  0  7  8 20 12 21  1  1]
[16 -7  9 24 23  9 -7 22 18 -6  0 23 14 14 17 14  0 -7 -8 20 12 21  1  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**2
2<< z>>2
1j*z
z/1/1


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
error

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.random.rand(4,4)
print(arr)
arr = np.round(arr,0)
print(arr)

[[0.93931552 0.56392286 0.60277984 0.98074011]
 [0.82480233 0.04378581 0.1390686  0.18710873]
 [0.47273013 0.47181949 0.10276771 0.35808273]
 [0.63642685 0.6726864  0.77251152 0.7140763 ]]
[[1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([5,6,7,8,9])
res=np.intersect1d(arr1,arr2)
print(res)

[5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
td=np.datetime64("today","D")
yst = np.datetime64("today",'D') - np.timedelta64(1)
tmrw = np.datetime64("today","D") + np.timedelta64(1)
print(td ,yst , tmrw , sep = "\n")

2024-08-17
2024-08-16
2024-08-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
date = np.arange('2016-07','2016-08',dtype ="datetime64[D]")
print(date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(a)
print()
print(b)
print()
np.add(a,b,out = b)
np.multiply(a,-0.5,out = a)
np.multiply(a,b, out = a )
print(a)


[[0.55604929 0.76338963 0.85695645]
 [0.57950415 0.3604696  0.30570486]
 [0.07378977 0.49991249 0.00313481]]

[[0.56879031 0.50714937 0.89166478]
 [0.30600043 0.31766648 0.32015747]
 [0.26394364 0.58835138 0.17521474]]

[[-3.12733129e-01 -4.84958152e-01 -7.49246118e-01]
 [-2.56576789e-01 -1.22223721e-01 -9.56645793e-02]
 [-1.24606357e-02 -2.72018347e-01 -2.79546086e-04]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr=np.random.uniform(0,10,10)
print(arr)
print()
# arr = np.floor(arr)
# arr = arr.astype(int)
# arr= np.trunc(arr)
# arr = (arr-arr%1)
print(arr)

[0.11347724 4.32707181 7.11089582 1.4357463  7.95489938 6.32373369
 3.96041637 9.94215224 9.64580758 7.5617202 ]

[0. 4. 7. 1. 7. 6. 3. 9. 9. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.arange(0,5).reshape(1,5)
arr = np.tile(arr,(5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def arr_gen(arr1):
  for i in range(10):
    x = np.random.randint(100)
    arr1 = np.append(arr1,x)
  return (arr1)
arr1 = np.array([])
print(arr_gen(arr1))

[89. 41. 34. 22. 31. 17.  4. 37. 43. 27.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = np.linspace(0,1,11,endpoint=False )[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vec =np.random.rand(10)
vec= np.sort(vec,axis=-1)
print(vec)

[0.10567168 0.16213219 0.32187081 0.36967396 0.44831976 0.47654382
 0.54084413 0.57637376 0.64822266 0.94640081]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.arange(9)
print(arr)
print()
sum = np.add.reduce(arr)
print(sum)

[0 1 2 3 4 5 6 7 8]

36


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(3,3)
print(A)
print()
B =np.random.rand(3,3)
print(B)
print()
if (A == B).all() :
  print("a and b r equal")
else:
  print("they arent equal")

[[0.61526806 0.16614232 0.82584367]
 [0.75235669 0.8624983  0.79746728]
 [0.93413903 0.85405623 0.58229522]]

[[0.67940971 0.37357315 0.8938623 ]
 [0.35306542 0.20193417 0.29751506]
 [0.96759381 0.77718689 0.39901656]]

they arent equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1,2,3,4,5])
arr.flags.writeable=False
arr[0]=100
print(arr)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr=np.random.rand(20).reshape(10,2)
print(arr)
print()
x , y = arr[:,0] ,arr[:,1]
radius = np.sqrt( x**2 + y**2)
theta =  np.arctan2(y,x)
radius = radius.reshape(-1,1)
theta = radius.reshape(-1,1)
polar = np.hstack((radius,theta))
print(polar)







[[0.28569631 0.07243554]
 [0.36096762 0.67074459]
 [0.23464321 0.34598537]
 [0.75303931 0.8646715 ]
 [0.46733182 0.52166698]
 [0.89340476 0.57443332]
 [0.21202627 0.35815645]
 [0.04043831 0.66253105]
 [0.54110341 0.08572121]
 [0.37332216 0.14039078]]

[[0.29473597 0.29473597]
 [0.76170593 0.76170593]
 [0.41804703 0.41804703]
 [1.14661458 1.14661458]
 [0.70038237 0.70038237]
 [1.06214203 1.06214203]
 [0.4162105  0.4162105 ]
 [0.663764   0.663764  ]
 [0.54785128 0.54785128]
 [0.39884709 0.39884709]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vec = np.random.rand(10)
print(vec)
print()
vec[np.argmax(vec)] = 0
print(vec)

[0.58926581 0.56439924 0.2486576  0.37078342 0.60968499 0.44303052
 0.8407799  0.9045257  0.3981997  0.17560133]

[0.58926581 0.56439924 0.2486576  0.37078342 0.60968499 0.44303052
 0.8407799  0.         0.3981997  0.17560133]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
############################################################################

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x = np.array([1,2,3,4,5,6])
y = np.array([7,8,9,10,11,12])
x = x.reshape(-1,1)
y = y.reshape(-1,1)
c = np.array([])
c = 1/ (x-y)
print(c)

[[-0.16666667]
 [-0.16666667]
 [-0.16666667]
 [-0.16666667]
 [-0.16666667]
 [-0.16666667]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for x in [np.int8, np.int32, np.int64,np.float32, np.float64]:
   if np.issubdtype(x,np.integer):
    print(x)
    print(np.iinfo(x).min)
    print(np.iinfo(x).max)
    print("---------------------------------")
   elif (np.issubdtype(x,np.floating)):
      print(x)
      print(np.finfo(x).min)
      print(np.finfo(x).max)
      print("---------------------------------")


<class 'numpy.int8'>
-128
127
---------------------------------
<class 'numpy.int32'>
-2147483648
2147483647
---------------------------------
<class 'numpy.int64'>
-9223372036854775808
9223372036854775807
---------------------------------
<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
---------------------------------
<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
---------------------------------


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr=np.arange(1000)
np.set_printoptions(threshold=float("inf"))


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
vec = np.array([3123,421,11,12456,1])
x = int(input("enter the num to find: "))
index = np.abs(vec-x).argmin()
print('closest val is: ',vec[index])

enter the num to find: 300
closest val is:  421


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
dtype = [
    ('x' , 'float'),
    ('y','float'),
    ('r','int'),
    ('g','int'),
    ('b','int')
]
arr = np.zeros(5 , dtype = dtype)
arr['x'] = np.random.rand(5)
arr['y'] = np.random.rand(5)
arr['r'] = np.random.randint(0,255,5)
arr['g'] = np.random.randint(0,255,5)
arr['b'] = np.random.randint(0,255,5)
print(arr)

[(0.34333655, 0.05977021, 238, 179, 146)
 (0.45074603, 0.90963593, 229,   3,   4)
 (0.11711429, 0.23103932, 239, 132,  37)
 (0.74208579, 0.24239371, 199,  79, 122)
 (0.92504559, 0.78091117, 118, 128,  65)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vec = np.random.rand(100,2)
x, y = np.atleast_2d(vec[:, 0], vec[:, 1])
r = np.sqrt((x-x.T) **2 +(y-y.T )**2 )
print(r)

[[0.         0.42122161 0.5771086  0.68951508 0.66837848 0.19539869
  0.02605808 0.48001625 0.82280268 0.46479153 0.63483066 1.00583063
  0.21626194 0.20773088 0.48766415 0.73410229 0.36956584 0.96920477
  0.64376455 0.4351896  0.63026655 0.45351121 1.04965406 0.55817823
  0.74089598 0.84145886 0.86758182 0.40372321 0.75569574 0.3882045
  0.68176455 0.42870532 0.1000789  0.55740377 0.80294386 0.70474722
  0.80825958 0.5484279  0.37702605 0.49131577 0.63307637 0.85663458
  0.6151977  0.90712427 0.61760792 0.75891984 0.45495762 0.93891924
  0.33959616 0.40598524 0.04190431 0.7734336  0.49309081 0.53381298
  0.79480515 0.66147051 0.72002144 0.80971599 0.69665602 0.46267067
  0.66242847 0.80643018 0.29469456 0.41968288 0.62898112 0.99624261
  0.2117586  0.82757497 0.66586277 0.74132078 0.54992156 0.18652115
  0.2536145  1.0012118  0.90045451 1.10705322 0.59019086 0.81450085
  0.41437874 0.64320357 0.65336968 0.63290957 0.88755229 0.88096509
  0.62049109 0.84975097 0.51862357 0.63442349 0.5

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr = np.random.rand(20)
print(arr)
arr = arr.astype('int32')
print(arr)

[0.97481396 0.70227299 0.4330701  0.94156099 0.24599867 0.14528611
 0.51621379 0.48538839 0.74760712 0.28015949 0.41192196 0.58517202
 0.97971591 0.93389957 0.18296288 0.75477876 0.13897748 0.87731749
 0.32742387 0.19243242]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
########################################

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.random.rand(10)
print(arr)
for item,index in np. ndenumerate(arr):
  print(f"index{index} vale:{item}")

[0.4121685  0.21546988 0.33467371 0.20739183 0.69229455 0.28137213
 0.7345031  0.81754403 0.91135031 0.15795508]
index0.4121684959074843 vale:(0,)
index0.21546987612984025 vale:(1,)
index0.33467370803282703 vale:(2,)
index0.2073918314944051 vale:(3,)
index0.6922945464632954 vale:(4,)
index0.2813721284442763 vale:(5,)
index0.734503104104887 vale:(6,)
index0.817544026602625 vale:(7,)
index0.911350310640298 vale:(8,)
index0.15795508148517712 vale:(9,)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
###############

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
arr = np.arange(25).reshape(5,5)
print(arr)
arr = arr.astype(object)
np.put(arr ,( np.random.choice(range(25) , 4 , replace = False )), 'p' )
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 'p' 3 4]
 [5 'p' 7 8 9]
 ['p' 11 12 13 14]
 [15 16 'p' 18 19]
 [20 21 22 23 24]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
mat = np.random.rand(20).reshape(5,4)
print(mat)
mean = mat.mean(axis=1 , keepdims= True)
new = mat - mean
print(new)

[[0.13264228 0.0542295  0.01156308 0.42400597]
 [0.81740942 0.84235493 0.72629715 0.56708749]
 [0.71536799 0.49387198 0.98831395 0.45834172]
 [0.63395    0.7806897  0.66891201 0.24031421]
 [0.66937269 0.92028207 0.79849763 0.23315533]]
[[-0.02296793 -0.10138071 -0.14404713  0.26839577]
 [ 0.07912218  0.10406768 -0.0119901  -0.17119976]
 [ 0.05139408 -0.17010193  0.32434004 -0.20563219]
 [ 0.05298352  0.19972322  0.08794553 -0.34065227]
 [ 0.01404576  0.26495514  0.1431707  -0.4221716 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
arr = np.random.rand(20).reshape(4,5)
print(arr)
n = int(input("enter the selected col: "))
sorted_indx = np.argsort(arr[:, n ])
sorted_mat = arr[sorted_indx]
print(sorted_mat)

[[0.7153746  0.87931955 0.22135654 0.34673271 0.6049678 ]
 [0.93388546 0.68599596 0.38231339 0.81621636 0.78384975]
 [0.56539957 0.59548851 0.6289475  0.85160994 0.82442869]
 [0.8209308  0.37118785 0.54920619 0.18503743 0.72885893]]
enter the selected col: 3
[3 0 1 2]
[[0.8209308  0.37118785 0.54920619 0.18503743 0.72885893]
 [0.7153746  0.87931955 0.22135654 0.34673271 0.6049678 ]
 [0.93388546 0.68599596 0.38231339 0.81621636 0.78384975]
 [0.56539957 0.59548851 0.6289475  0.85160994 0.82442869]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr1 = np.random.rand(20).reshape(5,4)
arr2 = np.zeros((3,3))
print(arr1)
if (not(~arr1.any(axis=0).any())) :
  print("there is no null")
else:
  print("there is null")

[[0.44574324 0.44057007 0.51577171 0.31231331]
 [0.43893901 0.62564481 0.81632788 0.54113845]
 [0.64423172 0.95317364 0.61704768 0.62177897]
 [0.42406737 0.61116225 0.39164708 0.77189093]
 [0.29477802 0.47211513 0.02373746 0.95411211]]
there is no null


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
vec = np.array([3123,421,11,12456,1])
x = int(input("enter the num to find: "))
index = np.abs(vec-x).argmin()
print('closest val is: ',vec[index])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.arange(3).reshape(3,1)
it = np.nditer([arr1,arr2,None])
print(np.sum(it))

27


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class array:
  def __init__(self,array,name) :
    self.array = array
    self.name = name
  def get_name(self):
    return (f"{self.name}, is the name of {self.array}")

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
z= np.array([1,2,3,4])
i = np.random.randint(0,1,20)
np.add.at(z,i ,1)
print(z)

[21  2  3  4]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
x = np.array([1,2,3,4,5,6])
l = [1,3,9,3,4,1]
F = np.bincount(l,x)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
###

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
print(np.sum(sum))

[[35 51 54 62]
 [62 58 48 63]
 [53 40 62 46]]
634


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
vec1 = np.array([1,2,3,4,5,6])

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
a1 = np.random.rand(20).reshape(5,4)
a2 = np.random.rand(20).reshape(4,5)
d = np.dot(a1,a2)
print(d)
diag = np.diag(d)
print(diag)

[[0.37123444 0.5766558  1.24139122 0.18275658 0.61256065]
 [0.52701978 1.3084117  2.17782808 0.18464357 1.2186392 ]
 [0.6636972  0.83944385 1.69894251 0.34326224 0.90186899]
 [0.60893187 0.52304005 1.34987157 0.37202411 0.67508408]
 [0.49498528 1.01671103 1.48611845 0.19163934 0.93231322]]
[0.37123444 1.3084117  1.69894251 0.37202411 0.93231322]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
v = np.array([1, 2, 3, 4, 5])
v2 = np.zeros((20))
v2[::4] = v
print(v2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
arr55 = 2*np.ones((5,5))
arr553 = np.ones((5,5,3))
mul = (arr553 * arr55[:,:,None])
print(mul)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.random.rand(25).reshape(5,5)
print(arr)
print()
arr[[0]] ,arr[[1]] = arr[[1]] , arr[[0]]
print(arr)

[[0.31064268 0.42532955 0.74180538 0.9604947  0.19992235]
 [0.67300494 0.31221935 0.89749251 0.30167795 0.78080013]
 [0.25342378 0.27654584 0.97401724 0.91909197 0.04795986]
 [0.7121034  0.70282843 0.70893437 0.46160655 0.68182757]
 [0.80564161 0.40406844 0.5949977  0.38957006 0.58747097]]

[[0.67300494 0.31221935 0.89749251 0.30167795 0.78080013]
 [0.31064268 0.42532955 0.74180538 0.9604947  0.19992235]
 [0.25342378 0.27654584 0.97401724 0.91909197 0.04795986]
 [0.7121034  0.70282843 0.70893437 0.46160655 0.68182757]
 [0.80564161 0.40406844 0.5949977  0.38957006 0.58747097]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)###########################################msh fahjm
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 29) ( 0, 36) ( 2, 58) ( 2, 96) ( 4, 65) ( 4, 70) ( 7, 46) ( 7, 75)
 ( 8, 47) ( 8, 48) ( 9, 52) ( 9, 73) (15, 77) (15, 83) (19, 79) (19, 92)
 (20, 36) (20, 58) (29, 36) (36, 58) (46, 75) (47, 48) (52, 73) (58, 96)
 (63, 85) (63, 92) (65, 70) (77, 83) (79, 92) (85, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
c=np.array([0,4,3,1,2,1,5,1])
a = np.repeat((np.arange(len(c))),c)
print(a)
print(bin)

[1 1 1 1 2 2 2 3 4 4 5 6 6 6 6 6 7]
[0 4 3 1 2 1 5 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
############################################

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [4]:
arr = np.array([1,1,1,2,2,2,2,2,2,2,2,3,4,5,6,7,9,9])
print(np.bincount(arr).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)